version: "3.4"

services:
  redis:
    container_name: "redis-server"
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  iot-db:
    restart: always
    container_name: "iot-db"
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=iot
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

volumes:
  data:
  logs:
